extends: default

ignore: templates

rules:
  new-line-at-end-of-file:
    level: warning
  trailing-spaces:
    level: warning
  line-length: disable
  document-start: disable
  indentation:
    spaces: consistent
    indent-sequences: consistent
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
    
