#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2022, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Create our VM instance"
  gather_facts: false
  hosts: localhost
  vars_files:
    - "config/aglais.yml"
    - "../../hadoop-yarn/ansible/config/ansible.yml"
    - "../../hadoop-yarn/ansible/config/openstack.yml"
  vars:
    nodename: "gitstore"
  tasks:

    # https://stackoverflow.com/a/56146697
    - name: "Include our status file [{{ statusfile }}]"
      include_vars:
        file: "{{statusfile}}"

    - name: "Create our [{{ nodename }}] VM"
      os_server:
        cloud: "{{ cloudname }}"
        state: present
        name:     "{{ deployname }}-{{ nodename }}"
        image:    "{{ hostvars[nodename]['image']  }}"
        flavor:   "{{ hostvars[nodename]['flavor'] }}"
        network:  "{{ openstack.networks.infraops.network.name }}"
        key_name: "{{ openstack.keypair.name }}"
        auto_ip: false
        meta:
          nodename: "{{ nodename }}"
        security_groups:
          - "{{ aglais.spec.openstack.security[nodename].id }}"
      register:
        serverobj

    - name: "Update our status file [{{ statusfile }}]"
      ansible.builtin.shell: |
        yq eval \
          --inplace \
          '
          .aglais.spec.openstack.hosts.{{ nodename }} = {
            "name": "{{ serverobj.openstack.name }}",
            "id": "{{ serverobj.openstack.id }}",
            "address": {
              "internal": "{{ serverobj.openstack.private_v4 }}"
              }
            }
          ' '{{ statusfile }}'


