#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2022, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Create our gitstore instance"
  gather_facts: false
  hosts: localhost
  vars_files:
    - "config/aglais.yml"
    - "../../hadoop-yarn/ansible/config/ansible.yml"
    - "../../hadoop-yarn/ansible/config/openstack.yml"
  vars:
    nodename: "gitstore"
  tasks:

    # https://stackoverflow.com/a/56146697
    - name: "Include our status file [{{ statusfile }}]"
      include_vars:
        file: "{{statusfile}}"

    - name: "Assign a floating IP address to our node"
      os_floating_ip:
        cloud: "{{ cloudname }}"
        state: present
        server:  "{{ aglais.spec.openstack.hosts[nodename].id }}"
        network: "{{ openstack.networks.external.name }}"
        nat_destination: "{{ openstack.networks.infraops.name }}"
      register:
        floatingip

    - name: "Apply our ssh security group to our floating IP address"
      os_port:
        cloud: "{{ cloudname }}"
        state: present
        name: '{{ floatingip.floating_ip.port }}'
        security_groups:
          - "{{ aglais.spec.openstack.security[nodename].id }}"

    - name: "Update our status file [{{ statusfile }}]"
      ansible.builtin.shell: |
        yq eval \
          --inplace \
          '
          .aglais.spec.openstack.hosts.{{ nodename }}.address.external = "{{ floatingip.floating_ip.floating_ip_address }}"
          ' '{{ statusfile }}'

