#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2021, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Configure Zeppelin ssh "
  hosts: zeppelin
  gather_facts: false
  vars_files:
    - config/aglais.yml
    - config/ansible.yml
    - config/zeppelin.yml
    - /opt/aglais/aglais-status.yml
  vars:
    zepkeytype: "rsa"
    zepkeyname: "id_{{zepkeytype}}"
    zeppubkeyfile: "/etc/ssh/zeppelin-{{zepkeytype}}.pub"
  tasks:

    - name: "Create Zeppelin's SSH directory"
      become: true
      ansible.builtin.file:
        path:  "{{zepuserhome}}/.ssh"
        owner: "{{zepuser}}"
        group: "{{zepuser}}"
        state: directory
        mode:  'u=rwx,g=,o='

    # https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html
    - name: "Generate Zeppelin's SSH keypair"
      become: true
      community.crypto.openssh_keypair:
        path:  "{{zepuserhome}}/.ssh/{{zepkeyname}}"
        owner: "{{zepuser}}"
        group: "{{zepuser}}"

#   - name: "Create our public keys directory [{{zeppubkeypath}}]"
#     become: true
#     ansible.builtin.file:
#       path:  "{{zeppubkeypath}}"
#       owner: 'root'
#       group: 'root'
#       state: directory
#       mode:  'u=rwx,g=rwx,o=rx'

    - name: "Save Zeppelin's public key as [{{zeppubkeyfile}}]"
      become: true
      ansible.builtin.copy:
        remote_src: true
        src:   "{{zepuserhome}}/.ssh/{{zepkeyname}}.pub"
        dest:  "{{zeppubkeyfile}}"
        owner: 'root'
        group: 'root'
        mode:  'u=r,g=r,o=r'

    # https://serverfault.com/questions/434896/ssh-one-authorized-keys-for-multiple-service-accounts
    # https://serverfault.com/a/1021416
    - name: "Add Zeppelin's public key to the global [AuthorizedKeysFile] list"
      become: true
      ansible.builtin.replace:
        path: "/etc/ssh/sshd_config"
        regexp:  "^(AuthorizedKeysFile).*$"
        replace: "\\1 .ssh/authorized_keys {{zeppubkeyfile}}"
        owner: root
        group: root
        mode: 'u=rw,g=,o='

#   - name: "Add the Zeppelin's public key to Zeppelin's authorized_keys"
#     become: true
#     ansible.builtin.shell: |
#       cat "{{zepuserhome}}/.ssh/{{zepkeyname}}.pub" \
#       >>  "{{zepuserhome}}/.ssh/authorized_keys"

    - name: "Add a fingerprint for [localhost] to known_hosts"
      become: true
      ansible.builtin.shell: |
        ssh-keyscan 'localhost' >> "{{zepuserhome}}/.ssh//known_hosts"

    - name: "Add a [localhost] config entry"
      ansible.builtin.blockinfile:
        path: "{{zepuserhome}}/.ssh/config"
        create: true
        block: |
            Host localhost
              IdentityFile ~/.ssh/{{zepkeyname}}
              IdentitiesOnly yes

    - name: "Set permissions and ownership on Zeppelin's [.ssh] directory"
      become: true
      ansible.builtin.file:
        recurse: true
        path:  "{{zepuserhome}}/.ssh"
        owner: "{{zepuser}}"
        group: "{{zepuser}}"
        state: directory
        mode:  'u=rwX,g=,o='

    - name: "Reload the [sshd] service"
      become: true
      ansible.builtin.systemd:
        name: sshd.service
        state: reloaded


