#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
# Based on ideas from Larry Smith Jr.
# https://everythingshouldbevirtual.com/automation/ansible-ssh-known-host-keys/
#

- name: "Create Linux user account [{{username}}]"
  hosts: zeppelin
  become: true
  gather_facts: false
  vars_files:
    - config/users.yml
    - config/ansible.yml
    - /opt/aglais/aglais-status.yml
  vars:
    temphome: "/tmp/{{username}}-home"
    zeppelinkeypath: "/opt/aglais/ssh/fedora-rsa.pub"
  tasks:

    - name: "Create Linux user account [{{username}}]"
      user:
        uid:  "{{useruid}}"
        name: "{{username}}"
        home: "{{userhome}}"
        state: present
        append: true
        groups:
            - users
        create_home: true

    - name: "Update directory owner"
      ansible.builtin.file:
        path:  "{{userhome}}"
        owner: "{{username}}"
        group: "{{username}}"

    - name: "Update directory mode"
      ansible.builtin.file:
        path: "{{userhome}}"
        mode: "u=rwx,g=x,o="

#   - name: "Update SELinux context"
#     ansible.builtin.file:
#       path: "{{temphome}}"
#       serole: "object_r"
#       setype: "user_home_dir_t"
#       seuser: "unconfined_u"

    - name: "Fetch the Zeppelin user's public key"
      ansible.builtin.slurp:
        src: "{{zeppelinkeypath}}"
      register: zeppelinkeyvalue

    - name: "Install the Zeppelin user's public key"
      become: true
      ansible.posix.authorized_key:
        key:  "{{ zeppelinkeyvalue['content'] | b64decode }}"
        user: "{{username}}"
        state: present

    - name: "Install the user's own public key"
      become: true
      ansible.posix.authorized_key:
        key:  "{{userpubkey}}"
        user: "{{username}}"
        state: present
      when: userpubkey is defined

    # https://github.com/ansible/ansible/issues/5632#issuecomment-249794114
#   - name: "Relocate user home [{{temphome}}][{{userhome}}]"
#     user:
#       name: "{{username}}"
#       home: "{{userhome}}"
#       state: present
#       move_home: true
#       create_home: false



