
name: CI

"on":
  pull_request:
    branches:
      - "master"

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: ".yamllint.yml"

      - name: Install test dependencies
        run: pip install -r deployments/common/pip/requirements.txt

